---
# Master yml file


###############################################################################
# Language groups                                                             #
###############################################################################

- hosts: python-dev
  roles:
    - python

- hosts: node-dev
  roles:
    - nodejs

###############################################################################
# Database groups                                                             #
###############################################################################

- hosts: mongodb-group
  roles:
    - mongodb

