---
# This playbook sets up most of what you would
# want in a python dev machine

- name: Install python headers
  apt: >
    name=python-dev
    update_cache=yes
    state=latest

- name: Install Pip, Virtualenv, and Setuptools
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - python-pip
    - python-virtualenv
    - python-setuptools

